### PR TITLE
[TASK] Add DDEV v1.24 and latest/nightly to build matrix

### PR DESCRIPTION
**Pull request by ochorocho**
Add DDEV 1.24 and latest/nightly to the list of versions to built docker images for.

### CODE REVIEW

**Comment by rfay** [comment]
Looks great to me, thanks so much for maintaining this! Do you think there would be value in adding DDEV HEAD in there as well? The great thing we get out of testing with HEAD in the add-ons is an early warning system if HEAD breaks some add-on.

**Comment by ochorocho** [comment]
@rfay how to get the binary for DDEV HEAD or do i have to build it myself? 

Any other recommondations before i start? :-)

Currently, just downloading the file from GitHub:
https://github.com/ddev/ddev-gitlab-ci/blob/main/ddev-install.sh#L23

**Comment by rfay** [comment]
DDEV HEAD is easy to get, but it's slightly different approach, https://ddev.readthedocs.io/en/stable/developers/building-contributing/#testing-latest-commits-on-head

Not trying to get in your way here. Sure appreciate the maintenance and leadership on this!

**Comment by ochorocho** [comment]
@rfay can you please have a quick look?
I've added  DDEV HEAD as latest tag.

**Review by rfay — APPROVED** [review]
Sure looks good to me... especially if it works :)

**Comment by ochorocho** [comment]
@rfay FYI, images are created once a week on Monday at 1:00am.
In case you think we should build it more frequently just let me know.

**Comment by rfay** [comment]
I just appreciate you doing it and noting if there's ever a problem. It also will likely be appreciated by some project that needs a feature in HEAD that's not in a release yet.

**Pull request merged**
